import "server-only";
import { Prisma, type PrismaClient } from "@prisma/client";
import { validateOperationalInterval } from "@/lib/booking/operational-interval";
import { acquireVehicleReservationLock } from "./advisory-lock";

// BOOKING-CONFLICT-1A — the ONE primitive that atomically commits a physical vehicle to a
// booking for a time window, guaranteeing a vehicle is never double-booked for overlapping
// intervals. It is a pure resource-reservation step: it does NOT transition the booking,
// write Booking.vehicleId / vehicleSnapshot, touch Payment, or emit a BookingStatusEvent —
// those remain acceptBooking's job (wired in BOOKING-CONFLICT-1B). This gate only adds the
// primitive; nothing calls it yet.
//
// It MUST run inside the caller's interactive transaction (the same tx that will later do
// the acceptance write), so the advisory lock, the overlap check, and the insert are one
// atomic unit under per-vehicle mutual exclusion:
//   1. validate the interval (half-open, startsAt < endsAt),
//   2. take the per-vehicle transaction-scoped advisory lock,
//   3. check for any ACTIVE (releasedAt IS NULL) overlapping reservation on this vehicle,
//   4. if none, insert the reservation (bookingId is UNIQUE — one reservation per booking).
// The SQL overlap predicate mirrors reservationIntervalsOverlap's half-open semantics
// exactly: touching boundaries do not conflict.

type DbClient = PrismaClient | Prisma.TransactionClient;

export type ReserveVehicleInput = {
  bookingId: string;
  vehicleId: string;
  startsAt: Date;
  endsAt: Date;
};

export type ReserveVehicleResult =
  | { ok: true; reservationId: string }
  // The requested window collides with an existing active reservation for this vehicle.
  | { ok: false; reason: "VEHICLE_BUSY" }
  // The interval itself is malformed (missing side / reversed / non-date).
  | { ok: false; reason: "INVALID_INTERVAL" }
  // A reservation already exists for this booking (bookingId UNIQUE) — a concurrent or
  // repeated reserve for the same booking. Surfaced distinctly, never a silent overwrite.
  | { ok: false; reason: "ALREADY_RESERVED" };

function isBookingUniqueViolation(error: unknown): boolean {
  if (!(error instanceof Prisma.PrismaClientKnownRequestError) || error.code !== "P2002") return false;
  const target = (error.meta as { target?: unknown } | undefined)?.target;
  // Prisma reports the offending unique field(s) in meta.target (array or string form).
  if (Array.isArray(target)) return target.includes("bookingId");
  if (typeof target === "string") return target.includes("bookingId");
  // Fallback: bookingId is the only application-level unique on this table, so any P2002
  // here is that constraint regardless of how the driver shaped meta.target.
  return true;
}

/**
 * Reserve a vehicle for a booking over [startsAt, endsAt). Call INSIDE an interactive
 * transaction. Returns a discriminated result; never throws for the expected outcomes
 * (busy / invalid / already-reserved). Does not mutate the booking or payment in any way.
 */
export async function reserveVehicleForBooking(
  tx: DbClient,
  input: ReserveVehicleInput,
): Promise<ReserveVehicleResult> {
  // 1. Interval validity — reuse the single interval authority so the reservation window
  //    obeys the same half-open, start<end rules as Booking.operationalStartAt/endAt.
  const validation = validateOperationalInterval(input.startsAt, input.endsAt);
  if (!validation.ok) return { ok: false, reason: "INVALID_INTERVAL" };
  const { startsAt, endsAt } = validation.interval;

  // 2. Per-vehicle mutual exclusion — everything below runs serialized for this vehicle.
  await acquireVehicleReservationLock(tx, input.vehicleId);

  // 3. Overlap check — any ACTIVE reservation on this vehicle intersecting [startsAt, endsAt).
  //    Half-open: "existing.startsAt < candidate.endsAt AND existing.endsAt > candidate.startsAt".
  const conflicts = await tx.$queryRaw<Array<{ id: string }>>`
    SELECT "id"
    FROM "vehicle_reservations"
    WHERE "vehicleId" = ${input.vehicleId}::uuid
      AND "releasedAt" IS NULL
      AND "startsAt" < ${endsAt}::timestamptz
      AND "endsAt" > ${startsAt}::timestamptz
    LIMIT 1
  `;
  if (conflicts.length > 0) return { ok: false, reason: "VEHICLE_BUSY" };

  // 4. Insert. id is app-generated by the uuid(7) default (ADR-0006). bookingId UNIQUE
  //    guards against a concurrent duplicate for the same booking (belt-and-braces beyond
  //    the advisory lock, which only serializes by vehicle, not by booking).
  try {
    const created = await tx.vehicleReservation.create({
      data: {
        bookingId: input.bookingId,
        vehicleId: input.vehicleId,
        startsAt,
        endsAt,
      },
      select: { id: true },
    });
    return { ok: true, reservationId: created.id };
  } catch (error) {
    if (isBookingUniqueViolation(error)) return { ok: false, reason: "ALREADY_RESERVED" };
    throw error;
  }
}
