import "server-only";
import type { BookingActorType, Prisma } from "@prisma/client";
import { prisma } from "@/lib/db";
import { transitionContract, dispatchContractHook, BookingContractNotFoundError, type ContractHookContext } from "./lifecycle";
import { getContractTemplate, type ContractTemplateKey } from "./templates/get-contract-template";
import type { BilingualText, ContractRenderContext } from "./templates/template";
import { resolveBookingChargeMoney } from "@/lib/booking/pricing/resolve-booking-money";

// Contract generation — Phase E.2. Renders the contract's template
// against its Booking's real data and transitions DRAFT -> GENERATED
// via the lifecycle engine (transition-contract.ts), all in one
// transaction. This is where requirement #5's "Version, Created Date,
// Generated By" become concrete: `generatedAt`/`generatedByActorType`/
// `generatedByActorId` are set here, exactly once per contract row —
// never again, since `content` is immutable after this (requirement #9).

function toBilingualText(value: unknown): BilingualText {
  if (value && typeof value === "object") {
    const obj = value as { ar?: unknown; en?: unknown };
    return {
      ar: typeof obj.ar === "string" ? obj.ar : "",
      en: typeof obj.en === "string" ? obj.en : "",
    };
  }
  return { ar: "", en: "" };
}

export interface GenerateContractContentParams {
  contractId: string;
  actorType: BookingActorType;
  actorId?: string;
}

export async function generateContractContent(params: GenerateContractContentParams): Promise<ContractHookContext> {
  const { contractId, actorType, actorId } = params;

  const contract = await prisma.bookingContract.findUnique({
    where: { id: contractId },
    include: {
      booking: {
        include: { service: true, provider: true },
      },
    },
  });

  if (!contract) {
    throw new BookingContractNotFoundError(contractId);
  }

  const generatedAt = new Date();
  const renderContext: ContractRenderContext = {
    bookingId: contract.bookingId,
    contractNumber: contract.contractNumber,
    serviceName: toBilingualText(contract.booking.service.name),
    providerName: toBilingualText(contract.booking.provider.businessName),
    priceAmount: contract.booking.priceSnapshotAmount?.toString() ?? "0",
    // The contract's authoritative amount is the effective total (unit × quantity for a
    // totalized booking; the historical unit for a legacy one). A contract is a document, not
    // a charge, so an unresolvable snapshot falls back to the unit rather than blocking
    // generation (a confirmed booking already passed acceptance's fail-closed money check).
    bookingTotal: (() => {
      const charge = resolveBookingChargeMoney(contract.booking);
      return charge.ok ? charge.money.total.toString() : contract.booking.priceSnapshotAmount?.toString() ?? "0";
    })(),
    priceCurrency: contract.booking.priceSnapshotCurrency ?? "OMR",
    seats: contract.booking.seats,
    generatedAt,
  };

  const template = getContractTemplate(contract.templateKey as ContractTemplateKey);
  const content = template.render(renderContext);

  const ctx = await prisma.$transaction(async (tx) => {
    await tx.bookingContract.update({
      where: { id: contractId },
      data: {
        content: content as unknown as Prisma.InputJsonValue,
        generatedAt,
        generatedByActorType: actorType,
        generatedByActorId: actorId ?? null,
      },
    });

    return transitionContract({ contractId, toStatus: "GENERATED", actorType, actorId }, tx);
  });

  await dispatchContractHook(ctx);
  return ctx;
}
